AllCops:
  Exclude:
    - vendor/**/*
    - tmp/**/*
    - Gemfile
    - spec/spec_helper.rb
    - spec/rails_helper.rb
    - db/**/*
    - config/**/*
    - bin/**/*
    - Guardfile
    - node_modules/*/**
