AllCops:
  Exclude:
    - vendor/**/*
    - tmp/**/*
    - Gemfile
    - spec/spec_helper.rb
    - spec/rails_helper.rb
    - db/**/*
    - config/**/*
    - bin/**/*
    - Guardfile
    - node_modules/**/*

# Maximum line length of 120 chars
Style/LineLength:
  Max: 120
  Enabled: true
