default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: personal_website

test:
  <<: *default
  database: personal_website_test

production:
  <<: *default
  database: personal_website
